version: '3.8'

services:
    chain-reaction:
        container_name: chain-reaction
        build:
            context: .
        depends_on:
            - database
        ports:
            - 3000:3000
        environment:
            - DB_SCHEMA=blog_posts
            - DB_HOST=database
            - DB_PASSWORD=Adam@2020
            - DB_PORT=5432
            - DB_USER=postgres
            - PORT=4000
            - JWT_SECRET=jpL5Xm6QwStzvB#2W6rPc4FgZ1D8nAq
        command: yarn start

    database:
        container_name: database
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Adam@2020
            - POSTGRES_DB=blog_posts
        volumes:
            - database-data:/var/lib/postgresql/data/
        ports:
            - 2345:5432
volumes:
    database-data:
